[package]
name = "weresocool"
version = "0.2.0"
authors = ["Danny Meyer <Danny.Meyer@gmail.com>"]
description = "***** WereSoCool __!Now In Stereo!__ ****** Make cool sounds. Impress your friends."
license = "MIT"
autobins = false

[dependencies]
portaudio = "0.7.0"
rand = "0.5.1"
hound = "3.4.0"


[[bin]]
name = "mic"
path = "bin/mic.rs"

[[bin]]
name = "composer"
path = "bin/composer.rs"

[[bin]]
name = "print"
path = "bin/print.rs"

[[bin]]
name = "scratch"
path = "bin/scratch.rs"
